### ISSUE TITLE
saluti

### ISSUE THREAD

**Issue by FabioZTessitore** [Giandomenico-bit/C#1]
Sei Iameo, giusto?

**Comment by Giandomenico-bit** [comment]
Sisi

**Comment by FabioZTessitore** [comment]
Vuoi riprendere il lab?

**Comment by Giandomenico-bit** [comment]
Si.  Non riuscendo a recuperare il mio vecchio account, ne ho creato uno nuovo

**Comment by FabioZTessitore** [comment]
per il resto tutto ok, che stai facendo?

riguardo agli esercizi cerca di utilizzare le repository come indicato negli esercizi sennò non li trovo e ricordati di aggiungermi come collaboratore

**Comment by Giandomenico-bit** [comment]
Si tutt’ok sto frequentando l’università di informatica alla federico II.

Per quando riguarda il laboratorio ho voluto creare repository per diversi
tipi di linguaggi per meglio organizzarmi il lavoro.

Il giorno mer 30 ott 2019 alle 13:23 Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
ok mi fa piacere.

sei libero di organizzare il lavoro come meglio credi, ma in fase di correzione metti nelle repo indicate. Poi una volta finito li sposti

**Comment by Giandomenico-bit** [comment]
Ok tutto chiaro.
