### ISSUE TITLE
cerchio

### ISSUE THREAD

**Issue by FabioZTessitore** [Giandomenico-bit/C#3]
```c
int raggio;
float circonferenza ,area;
...
circonferenza = 2 * Pi * raggio;
```

1. lo spazio si mette dopo la virgola e non prima (non si può guardare proprio!)
1. nel calcolo meglio mettere `2.` evidenziando che si tratta di floating point
1. quando si utilizzano variabili singole di tipo floating point è meglio usare double (tanto prima della stampa vengono comunque convertite a double e non hai risparmiato niente)

**Comment by Giandomenico-bit** [comment]
Il primo punto e' stato un errore mio di distrazione e anche il secondo.
