### ISSUE TITLE
maggiore5

### ISSUE THREAD

**Issue by FabioZTessitore** [Giandomenico-bit/C#5]
se l'esercizio avesse chiesto di trovare il maggiore tra 1000 che facevi?

bisogna utilizzare una strategia simile a maggiore2

**Comment by Giandomenico-bit** [comment]
Si esatto. Ma utilizzando if-else il programma sarebbe diventato concettualmente lo stesso poichè dovrò effettuare n confronti per ogni valore di input. Tuttavia, sempre parlando in termini di prestazioni anche se in questo caso non serve, i salti condizionati rallentano di molto il programma.

**Comment by FabioZTessitore** [comment]
con tanti valori non puoi farne a meno. Ripeto, stessa logica di maggiore2

**Comment by Giandomenico-bit** [comment]
Fatto

**Comment by FabioZTessitore** [comment]
ok, spero ti sia chiaro che questo algoritmo può andare in ciclo e trovare il massimo anche tra un milione di elementi, quello di prima no

**Comment by Giandomenico-bit** [comment]
Si ora si
